//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
namespace Ufba.Ev
{
	/// <summary>
	/// DomainRelationship EvModelHasElements
	/// Embedding relationship between the Model and Elements
	/// </summary>
	[DslDesign::DisplayNameResource("Ufba.Ev.EvModelHasElements.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Ufba.Ev.EvModelHasElements.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Ufba.Ev.EvDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("4f4a2f72-45fd-4cae-99ba-9e9fdeca8713")]
	public partial class EvModelHasElements : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// EvModelHasElements domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x4f4a2f72, 0x45fd, 0x4cae, 0x99, 0xba, 0x9e, 0x9f, 0xde, 0xca, 0x87, 0x13);
	
				
		/// <summary>
		/// Constructor
		/// Creates a EvModelHasElements link in the same Partition as the given EvModel
		/// </summary>
		/// <param name="source">EvModel to use as the source of the relationship.</param>
		/// <param name="target">Option to use as the target of the relationship.</param>
		public EvModelHasElements(EvModel source, Option target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(EvModelHasElements.EvModelDomainRoleId, source), new DslModeling::RoleAssignment(EvModelHasElements.ElementDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EvModelHasElements(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EvModelHasElements(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public EvModelHasElements(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public EvModelHasElements(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region EvModel domain role code
		
		/// <summary>
		/// EvModel domain role Id.
		/// </summary>
		public static readonly global::System.Guid EvModelDomainRoleId = new global::System.Guid(0xe35a2fd8, 0xa311, 0x4726, 0x86, 0xd1, 0x7d, 0x79, 0x47, 0x20, 0xa1, 0x0f);
		
		/// <summary>
		/// DomainRole EvModel
		/// </summary>
		[DslDesign::DisplayNameResource("Ufba.Ev.EvModelHasElements/EvModel.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Ufba.Ev.EvModelHasElements/EvModel.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Elements", PropertyDisplayNameKey="Ufba.Ev.EvModelHasElements/EvModel.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("e35a2fd8-a311-4726-86d1-7d794720a10f")]
		public virtual EvModel EvModel
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (EvModel)DslModeling::DomainRoleInfo.GetRolePlayer(this, EvModelDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, EvModelDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access EvModel of a Option
		/// <summary>
		/// Gets EvModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static EvModel GetEvModel(Option element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, ElementDomainRoleId) as EvModel;
		}
		
		/// <summary>
		/// Sets EvModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetEvModel(Option element, EvModel newEvModel)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, ElementDomainRoleId, newEvModel);
		}
		#endregion
		#region Element domain role code
		
		/// <summary>
		/// Element domain role Id.
		/// </summary>
		public static readonly global::System.Guid ElementDomainRoleId = new global::System.Guid(0xd1ed1b5a, 0xab31, 0x445b, 0xba, 0x89, 0x74, 0x8c, 0x51, 0xaf, 0xd8, 0xf3);
		
		/// <summary>
		/// DomainRole Element
		/// </summary>
		[DslDesign::DisplayNameResource("Ufba.Ev.EvModelHasElements/Element.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Ufba.Ev.EvModelHasElements/Element.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "EvModel", PropertyDisplayNameKey="Ufba.Ev.EvModelHasElements/Element.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("d1ed1b5a-ab31-445b-ba89-748c51afd8f3")]
		public virtual Option Element
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Option)DslModeling::DomainRoleInfo.GetRolePlayer(this, ElementDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, ElementDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Elements of a EvModel
		/// <summary>
		/// Gets a list of Elements.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Option> GetElements(EvModel element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Option>, Option>(element, EvModelDomainRoleId);
		}
		#endregion
		#region EvModel link accessor
		/// <summary>
		/// Get the list of EvModelHasElements links to a EvModel.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Ufba.Ev.EvModelHasElements> GetLinksToElements ( global::Ufba.Ev.EvModel evModelInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.EvModelHasElements>(evModelInstance, global::Ufba.Ev.EvModelHasElements.EvModelDomainRoleId);
		}
		#endregion
		#region Element link accessor
		/// <summary>
		/// Get the EvModelHasElements link to a Option.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Ufba.Ev.EvModelHasElements GetLinkToEvModel (global::Ufba.Ev.Option elementInstance)
		{
			global::System.Collections.Generic.IList<global::Ufba.Ev.EvModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.EvModelHasElements>(elementInstance, global::Ufba.Ev.EvModelHasElements.ElementDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Element not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region EvModelHasElements instance accessors
		
		/// <summary>
		/// Get any EvModelHasElements links between a given EvModel and a Option.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Ufba.Ev.EvModelHasElements> GetLinks( global::Ufba.Ev.EvModel source, global::Ufba.Ev.Option target )
		{
			global::System.Collections.Generic.List<global::Ufba.Ev.EvModelHasElements> outLinks = new global::System.Collections.Generic.List<global::Ufba.Ev.EvModelHasElements>();
			global::System.Collections.Generic.IList<global::Ufba.Ev.EvModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.EvModelHasElements>(source, global::Ufba.Ev.EvModelHasElements.EvModelDomainRoleId);
			foreach ( global::Ufba.Ev.EvModelHasElements link in links )
			{
				if ( target.Equals(link.Element) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one EvModelHasElements link between a given EvModeland a Option.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Ufba.Ev.EvModelHasElements GetLink( global::Ufba.Ev.EvModel source, global::Ufba.Ev.Option target )
		{
			global::System.Collections.Generic.IList<global::Ufba.Ev.EvModelHasElements> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.EvModelHasElements>(source, global::Ufba.Ev.EvModelHasElements.EvModelDomainRoleId);
			foreach ( global::Ufba.Ev.EvModelHasElements link in links )
			{
				if ( target.Equals(link.Element) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace Ufba.Ev
{
	/// <summary>
	/// DomainRelationship OptionHasFunctions
	/// Description for Ufba.Ev.OptionHasFunctions
	/// </summary>
	[DslDesign::DisplayNameResource("Ufba.Ev.OptionHasFunctions.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Ufba.Ev.OptionHasFunctions.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Ufba.Ev.EvDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("7c7047b7-f435-4984-b739-c6603a21f7c1")]
	public partial class OptionHasFunctions : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// OptionHasFunctions domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0x7c7047b7, 0xf435, 0x4984, 0xb7, 0x39, 0xc6, 0x60, 0x3a, 0x21, 0xf7, 0xc1);
	
				
		/// <summary>
		/// Constructor
		/// Creates a OptionHasFunctions link in the same Partition as the given Option
		/// </summary>
		/// <param name="source">Option to use as the source of the relationship.</param>
		/// <param name="target">Function to use as the target of the relationship.</param>
		public OptionHasFunctions(Option source, Function target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(OptionHasFunctions.OptionDomainRoleId, source), new DslModeling::RoleAssignment(OptionHasFunctions.FunctionDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public OptionHasFunctions(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public OptionHasFunctions(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public OptionHasFunctions(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public OptionHasFunctions(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Option domain role code
		
		/// <summary>
		/// Option domain role Id.
		/// </summary>
		public static readonly global::System.Guid OptionDomainRoleId = new global::System.Guid(0x0610bcea, 0xb612, 0x415d, 0x8c, 0xd8, 0xe0, 0x8b, 0x7f, 0xaf, 0x53, 0x16);
		
		/// <summary>
		/// DomainRole Option
		/// Description for Ufba.Ev.OptionHasFunctions.Option
		/// </summary>
		[DslDesign::DisplayNameResource("Ufba.Ev.OptionHasFunctions/Option.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Ufba.Ev.OptionHasFunctions/Option.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Functions", PropertyDisplayNameKey="Ufba.Ev.OptionHasFunctions/Option.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("0610bcea-b612-415d-8cd8-e08b7faf5316")]
		public virtual Option Option
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Option)DslModeling::DomainRoleInfo.GetRolePlayer(this, OptionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, OptionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Option of a Function
		/// <summary>
		/// Gets Option.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Option GetOption(Function element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, FunctionDomainRoleId) as Option;
		}
		
		/// <summary>
		/// Sets Option.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetOption(Function element, Option newOption)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, FunctionDomainRoleId, newOption);
		}
		#endregion
		#region Function domain role code
		
		/// <summary>
		/// Function domain role Id.
		/// </summary>
		public static readonly global::System.Guid FunctionDomainRoleId = new global::System.Guid(0x7c2c9e35, 0x6364, 0x4e00, 0xbb, 0x6a, 0xbb, 0x62, 0xf0, 0x93, 0x06, 0x66);
		
		/// <summary>
		/// DomainRole Function
		/// Description for Ufba.Ev.OptionHasFunctions.Function
		/// </summary>
		[DslDesign::DisplayNameResource("Ufba.Ev.OptionHasFunctions/Function.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Ufba.Ev.OptionHasFunctions/Function.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Option", PropertyDisplayNameKey="Ufba.Ev.OptionHasFunctions/Function.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("7c2c9e35-6364-4e00-bb6a-bb62f0930666")]
		public virtual Function Function
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Function)DslModeling::DomainRoleInfo.GetRolePlayer(this, FunctionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, FunctionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Functions of a Option
		/// <summary>
		/// Gets a list of Functions.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Function> GetFunctions(Option element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Function>, Function>(element, OptionDomainRoleId);
		}
		#endregion
		#region Param domain property code
		
		/// <summary>
		/// Param domain property Id.
		/// </summary>
		public static readonly global::System.Guid ParamDomainPropertyId = new global::System.Guid(0x5ac66e02, 0xfcce, 0x4a77, 0xa9, 0x29, 0x71, 0xcc, 0x68, 0xea, 0x7a, 0xc1);
		
		/// <summary>
		/// Storage for Param
		/// </summary>
		private global::System.String paramPropertyStorage = string.Empty;
		
		/// <summary>
		/// Gets or sets the value of Param domain property.
		/// Description for Ufba.Ev.OptionHasFunctions.Param
		/// </summary>
		[DslDesign::DisplayNameResource("Ufba.Ev.OptionHasFunctions/Param.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Ufba.Ev.OptionHasFunctions/Param.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainObjectId("5ac66e02-fcce-4a77-a929-71cc68ea7ac1")]
		public global::System.String Param
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return paramPropertyStorage;
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				ParamPropertyHandler.Instance.SetValue(this, value);
			}
		}
		/// <summary>
		/// Value handler for the OptionHasFunctions.Param domain property.
		/// </summary>
		internal sealed partial class ParamPropertyHandler : DslModeling::DomainPropertyValueHandler<OptionHasFunctions, global::System.String>
		{
			private ParamPropertyHandler() { }
		
			/// <summary>
			/// Gets the singleton instance of the OptionHasFunctions.Param domain property value handler.
			/// </summary>
			public static readonly ParamPropertyHandler Instance = new ParamPropertyHandler();
		
			/// <summary>
			/// Gets the Id of the OptionHasFunctions.Param domain property.
			/// </summary>
			public sealed override global::System.Guid DomainPropertyId
			{
				[global::System.Diagnostics.DebuggerStepThrough]
				get
				{
					return ParamDomainPropertyId;
				}
			}
			
			/// <summary>
			/// Gets a strongly-typed value of the property on specified element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <returns>Property value.</returns>
			public override sealed global::System.String GetValue(OptionHasFunctions element)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
				return element.paramPropertyStorage;
			}
		
			/// <summary>
			/// Sets property value on an element.
			/// </summary>
			/// <param name="element">Element which owns the property.</param>
			/// <param name="newValue">New property value.</param>
			public override sealed void SetValue(OptionHasFunctions element, global::System.String newValue)
			{
				if (element == null) throw new global::System.ArgumentNullException("element");
		
				global::System.String oldValue = GetValue(element);
				if (newValue != oldValue)
				{
					ValueChanging(element, oldValue, newValue);
					element.paramPropertyStorage = newValue;
					ValueChanged(element, oldValue, newValue);
				}
			}
		}
		
		#endregion
		#region Option link accessor
		/// <summary>
		/// Get the list of OptionHasFunctions links to a Option.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Ufba.Ev.OptionHasFunctions> GetLinksToFunctions ( global::Ufba.Ev.Option optionInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.OptionHasFunctions>(optionInstance, global::Ufba.Ev.OptionHasFunctions.OptionDomainRoleId);
		}
		#endregion
		#region Function link accessor
		/// <summary>
		/// Get the OptionHasFunctions link to a Function.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Ufba.Ev.OptionHasFunctions GetLinkToOption (global::Ufba.Ev.Function functionInstance)
		{
			global::System.Collections.Generic.IList<global::Ufba.Ev.OptionHasFunctions> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.OptionHasFunctions>(functionInstance, global::Ufba.Ev.OptionHasFunctions.FunctionDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Function not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region OptionHasFunctions instance accessors
		
		/// <summary>
		/// Get any OptionHasFunctions links between a given Option and a Function.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Ufba.Ev.OptionHasFunctions> GetLinks( global::Ufba.Ev.Option source, global::Ufba.Ev.Function target )
		{
			global::System.Collections.Generic.List<global::Ufba.Ev.OptionHasFunctions> outLinks = new global::System.Collections.Generic.List<global::Ufba.Ev.OptionHasFunctions>();
			global::System.Collections.Generic.IList<global::Ufba.Ev.OptionHasFunctions> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.OptionHasFunctions>(source, global::Ufba.Ev.OptionHasFunctions.OptionDomainRoleId);
			foreach ( global::Ufba.Ev.OptionHasFunctions link in links )
			{
				if ( target.Equals(link.Function) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one OptionHasFunctions link between a given Optionand a Function.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Ufba.Ev.OptionHasFunctions GetLink( global::Ufba.Ev.Option source, global::Ufba.Ev.Function target )
		{
			global::System.Collections.Generic.IList<global::Ufba.Ev.OptionHasFunctions> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.OptionHasFunctions>(source, global::Ufba.Ev.OptionHasFunctions.OptionDomainRoleId);
			foreach ( global::Ufba.Ev.OptionHasFunctions link in links )
			{
				if ( target.Equals(link.Function) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace Ufba.Ev
{
	/// <summary>
	/// DomainRelationship OptionHasCategories
	/// Description for Ufba.Ev.OptionHasCategories
	/// </summary>
	[DslDesign::DisplayNameResource("Ufba.Ev.OptionHasCategories.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Ufba.Ev.OptionHasCategories.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Ufba.Ev.EvDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("b2482601-abc8-4721-9401-838659fdefab")]
	public partial class OptionHasCategories : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// OptionHasCategories domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xb2482601, 0xabc8, 0x4721, 0x94, 0x01, 0x83, 0x86, 0x59, 0xfd, 0xef, 0xab);
	
				
		/// <summary>
		/// Constructor
		/// Creates a OptionHasCategories link in the same Partition as the given Option
		/// </summary>
		/// <param name="source">Option to use as the source of the relationship.</param>
		/// <param name="target">Category to use as the target of the relationship.</param>
		public OptionHasCategories(Option source, Category target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(OptionHasCategories.OptionDomainRoleId, source), new DslModeling::RoleAssignment(OptionHasCategories.CategoryDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public OptionHasCategories(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public OptionHasCategories(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public OptionHasCategories(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public OptionHasCategories(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Option domain role code
		
		/// <summary>
		/// Option domain role Id.
		/// </summary>
		public static readonly global::System.Guid OptionDomainRoleId = new global::System.Guid(0xc124a9c1, 0x5a72, 0x41a9, 0xbe, 0x5e, 0x43, 0xf7, 0xea, 0xc3, 0x0b, 0x47);
		
		/// <summary>
		/// DomainRole Option
		/// Description for Ufba.Ev.OptionHasCategories.Option
		/// </summary>
		[DslDesign::DisplayNameResource("Ufba.Ev.OptionHasCategories/Option.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Ufba.Ev.OptionHasCategories/Option.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Categories", PropertyDisplayNameKey="Ufba.Ev.OptionHasCategories/Option.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("c124a9c1-5a72-41a9-be5e-43f7eac30b47")]
		public virtual Option Option
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Option)DslModeling::DomainRoleInfo.GetRolePlayer(this, OptionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, OptionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Option of a Category
		/// <summary>
		/// Gets Option.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Option GetOption(Category element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, CategoryDomainRoleId) as Option;
		}
		
		/// <summary>
		/// Sets Option.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetOption(Category element, Option newOption)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, CategoryDomainRoleId, newOption);
		}
		#endregion
		#region Category domain role code
		
		/// <summary>
		/// Category domain role Id.
		/// </summary>
		public static readonly global::System.Guid CategoryDomainRoleId = new global::System.Guid(0x8723d0d8, 0x3352, 0x4902, 0xbb, 0x66, 0xf5, 0x1f, 0x08, 0x2d, 0x41, 0x8f);
		
		/// <summary>
		/// DomainRole Category
		/// Description for Ufba.Ev.OptionHasCategories.Category
		/// </summary>
		[DslDesign::DisplayNameResource("Ufba.Ev.OptionHasCategories/Category.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Ufba.Ev.OptionHasCategories/Category.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Option", PropertyDisplayNameKey="Ufba.Ev.OptionHasCategories/Category.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("8723d0d8-3352-4902-bb66-f51f082d418f")]
		public virtual Category Category
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Category)DslModeling::DomainRoleInfo.GetRolePlayer(this, CategoryDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, CategoryDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Categories of a Option
		/// <summary>
		/// Gets a list of Categories.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Category> GetCategories(Option element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Category>, Category>(element, OptionDomainRoleId);
		}
		#endregion
		#region Option link accessor
		/// <summary>
		/// Get the list of OptionHasCategories links to a Option.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Ufba.Ev.OptionHasCategories> GetLinksToCategories ( global::Ufba.Ev.Option optionInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.OptionHasCategories>(optionInstance, global::Ufba.Ev.OptionHasCategories.OptionDomainRoleId);
		}
		#endregion
		#region Category link accessor
		/// <summary>
		/// Get the OptionHasCategories link to a Category.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Ufba.Ev.OptionHasCategories GetLinkToOption (global::Ufba.Ev.Category categoryInstance)
		{
			global::System.Collections.Generic.IList<global::Ufba.Ev.OptionHasCategories> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.OptionHasCategories>(categoryInstance, global::Ufba.Ev.OptionHasCategories.CategoryDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Category not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region OptionHasCategories instance accessors
		
		/// <summary>
		/// Get any OptionHasCategories links between a given Option and a Category.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Ufba.Ev.OptionHasCategories> GetLinks( global::Ufba.Ev.Option source, global::Ufba.Ev.Category target )
		{
			global::System.Collections.Generic.List<global::Ufba.Ev.OptionHasCategories> outLinks = new global::System.Collections.Generic.List<global::Ufba.Ev.OptionHasCategories>();
			global::System.Collections.Generic.IList<global::Ufba.Ev.OptionHasCategories> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.OptionHasCategories>(source, global::Ufba.Ev.OptionHasCategories.OptionDomainRoleId);
			foreach ( global::Ufba.Ev.OptionHasCategories link in links )
			{
				if ( target.Equals(link.Category) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one OptionHasCategories link between a given Optionand a Category.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Ufba.Ev.OptionHasCategories GetLink( global::Ufba.Ev.Option source, global::Ufba.Ev.Category target )
		{
			global::System.Collections.Generic.IList<global::Ufba.Ev.OptionHasCategories> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.OptionHasCategories>(source, global::Ufba.Ev.OptionHasCategories.OptionDomainRoleId);
			foreach ( global::Ufba.Ev.OptionHasCategories link in links )
			{
				if ( target.Equals(link.Category) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
namespace Ufba.Ev
{
	/// <summary>
	/// DomainRelationship OptionHasCommands
	/// Description for Ufba.Ev.OptionHasCommands
	/// </summary>
	[DslDesign::DisplayNameResource("Ufba.Ev.OptionHasCommands.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Ufba.Ev.OptionHasCommands.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
	[DslModeling::DomainModelOwner(typeof(global::Ufba.Ev.EvDomainModel))]
	[global::System.CLSCompliant(true)]
	[DslModeling::DomainRelationship(IsEmbedding=true)]
	[DslModeling::DomainObjectId("f378e9b2-9af7-454f-8344-2f01eede5025")]
	public partial class OptionHasCommands : DslModeling::ElementLink
	{
		#region Constructors, domain class Id
		
		/// <summary>
		/// OptionHasCommands domain class Id.
		/// </summary>
		public static readonly new global::System.Guid DomainClassId = new global::System.Guid(0xf378e9b2, 0x9af7, 0x454f, 0x83, 0x44, 0x2f, 0x01, 0xee, 0xde, 0x50, 0x25);
	
				
		/// <summary>
		/// Constructor
		/// Creates a OptionHasCommands link in the same Partition as the given Option
		/// </summary>
		/// <param name="source">Option to use as the source of the relationship.</param>
		/// <param name="target">Command to use as the target of the relationship.</param>
		public OptionHasCommands(Option source, Command target)
			: base((source != null ? source.Partition : null), new DslModeling::RoleAssignment[]{new DslModeling::RoleAssignment(OptionHasCommands.OptionDomainRoleId, source), new DslModeling::RoleAssignment(OptionHasCommands.CommandDomainRoleId, target)}, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public OptionHasCommands(DslModeling::Store store, params DslModeling::RoleAssignment[] roleAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="store">Store where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public OptionHasCommands(DslModeling::Store store, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(store != null ? store.DefaultPartitionForClass(DomainClassId) : null, roleAssignments, propertyAssignments)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		public OptionHasCommands(DslModeling::Partition partition, params DslModeling::RoleAssignment[] roleAssignments)
			: base(partition, roleAssignments, null)
		{
		}
		
		/// <summary>
		/// Constructor
		/// </summary>
		/// <param name="partition">Partition where new link is to be created.</param>
		/// <param name="roleAssignments">List of relationship role assignments.</param>
		/// <param name="propertyAssignments">List of properties assignments to set on the new link.</param>
		public OptionHasCommands(DslModeling::Partition partition, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
			: base(partition, roleAssignments, propertyAssignments)
		{
		}
		#endregion
		#region Option domain role code
		
		/// <summary>
		/// Option domain role Id.
		/// </summary>
		public static readonly global::System.Guid OptionDomainRoleId = new global::System.Guid(0x2badeb65, 0x5ed6, 0x4030, 0xbc, 0xe6, 0x7b, 0xd5, 0xbc, 0x2e, 0xde, 0x94);
		
		/// <summary>
		/// DomainRole Option
		/// Description for Ufba.Ev.OptionHasCommands.Option
		/// </summary>
		[DslDesign::DisplayNameResource("Ufba.Ev.OptionHasCommands/Option.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Ufba.Ev.OptionHasCommands/Option.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Source, PropertyName = "Commands", PropertyDisplayNameKey="Ufba.Ev.OptionHasCommands/Option.PropertyDisplayName",  PropagatesCopy = DslModeling::PropagatesCopyOption.PropagatesCopyToLinkAndOppositeRolePlayer, Multiplicity = DslModeling::Multiplicity.ZeroMany)]
		[DslModeling::DomainObjectId("2badeb65-5ed6-4030-bce6-7bd5bc2ede94")]
		public virtual Option Option
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Option)DslModeling::DomainRoleInfo.GetRolePlayer(this, OptionDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, OptionDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Option of a Command
		/// <summary>
		/// Gets Option.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static Option GetOption(Command element)
		{
			return DslModeling::DomainRoleInfo.GetLinkedElement(element, CommandDomainRoleId) as Option;
		}
		
		/// <summary>
		/// Sets Option.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static void SetOption(Command element, Option newOption)
		{
			DslModeling::DomainRoleInfo.SetLinkedElement(element, CommandDomainRoleId, newOption);
		}
		#endregion
		#region Command domain role code
		
		/// <summary>
		/// Command domain role Id.
		/// </summary>
		public static readonly global::System.Guid CommandDomainRoleId = new global::System.Guid(0x365a3858, 0x8efb, 0x4194, 0xac, 0x12, 0x16, 0x10, 0xc7, 0xa1, 0x70, 0x36);
		
		/// <summary>
		/// DomainRole Command
		/// Description for Ufba.Ev.OptionHasCommands.Command
		/// </summary>
		[DslDesign::DisplayNameResource("Ufba.Ev.OptionHasCommands/Command.DisplayName", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslDesign::DescriptionResource("Ufba.Ev.OptionHasCommands/Command.Description", typeof(global::Ufba.Ev.EvDomainModel), "Ufba.Ev.GeneratedCode.DomainModelResx")]
		[DslModeling::DomainRole(DslModeling::DomainRoleOrder.Target, PropertyName = "Option", PropertyDisplayNameKey="Ufba.Ev.OptionHasCommands/Command.PropertyDisplayName", PropagatesDelete = true,  PropagatesCopy = DslModeling::PropagatesCopyOption.DoNotPropagateCopy, Multiplicity = DslModeling::Multiplicity.One)]
		[DslModeling::DomainObjectId("365a3858-8efb-4194-ac12-1610c7a17036")]
		public virtual Command Command
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return (Command)DslModeling::DomainRoleInfo.GetRolePlayer(this, CommandDomainRoleId);
			}
			[global::System.Diagnostics.DebuggerStepThrough]
			set
			{
				DslModeling::DomainRoleInfo.SetRolePlayer(this, CommandDomainRoleId, value);
			}
		}
				
		#endregion
		#region Static methods to access Commands of a Option
		/// <summary>
		/// Gets a list of Commands.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static DslModeling::LinkedElementCollection<Command> GetCommands(Option element)
		{
			return GetRoleCollection<DslModeling::LinkedElementCollection<Command>, Command>(element, OptionDomainRoleId);
		}
		#endregion
		#region Option link accessor
		/// <summary>
		/// Get the list of OptionHasCommands links to a Option.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Ufba.Ev.OptionHasCommands> GetLinksToCommands ( global::Ufba.Ev.Option optionInstance )
		{
			return DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.OptionHasCommands>(optionInstance, global::Ufba.Ev.OptionHasCommands.OptionDomainRoleId);
		}
		#endregion
		#region Command link accessor
		/// <summary>
		/// Get the OptionHasCommands link to a Command.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Ufba.Ev.OptionHasCommands GetLinkToOption (global::Ufba.Ev.Command commandInstance)
		{
			global::System.Collections.Generic.IList<global::Ufba.Ev.OptionHasCommands> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.OptionHasCommands>(commandInstance, global::Ufba.Ev.OptionHasCommands.CommandDomainRoleId);
			global::System.Diagnostics.Debug.Assert(links.Count <= 1, "Multiplicity of Command not obeyed.");
			if ( links.Count == 0 )
			{
				return null;
			}
			else
			{
				return links[0];
			}
		}
		#endregion
		#region OptionHasCommands instance accessors
		
		/// <summary>
		/// Get any OptionHasCommands links between a given Option and a Command.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::System.Collections.ObjectModel.ReadOnlyCollection<global::Ufba.Ev.OptionHasCommands> GetLinks( global::Ufba.Ev.Option source, global::Ufba.Ev.Command target )
		{
			global::System.Collections.Generic.List<global::Ufba.Ev.OptionHasCommands> outLinks = new global::System.Collections.Generic.List<global::Ufba.Ev.OptionHasCommands>();
			global::System.Collections.Generic.IList<global::Ufba.Ev.OptionHasCommands> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.OptionHasCommands>(source, global::Ufba.Ev.OptionHasCommands.OptionDomainRoleId);
			foreach ( global::Ufba.Ev.OptionHasCommands link in links )
			{
				if ( target.Equals(link.Command) )
				{
					outLinks.Add(link);
				}
			}
			return outLinks.AsReadOnly();
		}
		/// <summary>
		/// Get the one OptionHasCommands link between a given Optionand a Command.
		/// </summary>
		[global::System.Diagnostics.DebuggerStepThrough]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
		public static global::Ufba.Ev.OptionHasCommands GetLink( global::Ufba.Ev.Option source, global::Ufba.Ev.Command target )
		{
			global::System.Collections.Generic.IList<global::Ufba.Ev.OptionHasCommands> links = DslModeling::DomainRoleInfo.GetElementLinks<global::Ufba.Ev.OptionHasCommands>(source, global::Ufba.Ev.OptionHasCommands.OptionDomainRoleId);
			foreach ( global::Ufba.Ev.OptionHasCommands link in links )
			{
				if ( target.Equals(link.Command) )
				{
					return link;
				}
			}
			return null;
		}
		
		#endregion
	}
}
