//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ufba.Ev
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "visualEv";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"Ev";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Ufba";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID EvDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EvCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID EvExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EvCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewEvExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(EvCommandSetId), 0x0001);
	
		// Package identifier
		public const string EvPackageId = "623cb3cb-ecfa-457c-8465-c0634384012d";
		
		// Editor factory identifier
		public const string EvEditorFactoryId = "9e65415c-6a24-47d4-b4fd-71ab2dce39da";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string EvModelExplorerToolWindowId = "32284ea2-41db-409c-b31b-4df79fabcf65";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Ufba.Ev
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string EvCommandSetId = "c64d6e8a-ce54-4f7b-af2b-f37c48631ed4";
	}
}